---
version: 2
jobs:
  build:
    working_directory: /Pink2
    docker:
      - image: ubuntu:trusty
        environment:
          FROM_BUILD: "JRedinger"
    steps:
      - checkout
      - run:
          name: Install Build Depends
          command: |
                  echo APT::Install-Recommends "0"; >> /etc/apt/apt.conf && \
                  echo APT::Install-Suggests "0"; >> /etc/apt/apt.conf && \
                  apt-get update && apt-get install \
                  --no-install-recommends \
                  -y \
                  wget g++ ca-certificates p7zip-full autoconf automake bash bzip2 cmake gettext git libtool make g++-mingw-w64-x86-64
      - run:
          name: Build BOOST
          command: |
                 cd src
                 wget https://sourceforge.net/projects/boost/files/boost/1.57.0/boost_1_57_0.tar.gz
                 echo 'fea9c7472f7a52cec2a1640958145b2144bf17903a21db65b95efb6ae5817fa5  boost_1_57_0.tar.gz' | sha256sum -c
                 tar xvzf boost_1_57_0.tar.gz
                 cd boost_1_57_0
                 echo "using gcc : : x86_64-w64-mingw32-g++ : <cxxflags>\"-std=c++11 -fvisibility=hidden     -I/usr/x86_64-w64-mingw32/include    \"  <linkflags>\"-L/usr/x86_64-w64-mingw32/lib    \" <archiver>\"x86_64-w64-mingw32-ar\" <striper>\"x86_64-w64-mingw32-strip\"  <ranlib>\"x86_64-w64-mingw32-ranlib\" <rc>\"\" : ;" > user-config.jam
                 ./bootstrap.sh --without-icu --with-libraries=chrono,filesystem,program_options,system,thread,test
                 ./b2 -d2 -j2 -d1 --prefix=/usr/x86_64-w64-mingw32 variant=release --layout=tagged --build-type=complete --user-config=user-config.jam threading=multi link=static -sNO_BZIP2=1 -sNO_ZLIB=1 binary-format=pe target-os=windows threadapi=win32 runtime-link=static address-model=64 stage
                 ./b2 -d0 -j4 --prefix=/usr/x86_64-w64-mingw32 variant=release --layout=tagged --build-type=complete --user-config=user-config.jam threading=multi link=static -sNO_BZIP2=1 -sNO_ZLIB=1 binary-format=pe target-os=windows threadapi=win32 runtime-link=static address-model=64 install
      - run:
          name: Build ZLib
          command: |
                 cd src
                 wget http://www.zlib.net/zlib-1.2.11.tar.gz
                 echo 'c3e5e9fdd5004dcb542feda5ee4f0ff0744628baf8ed2dd5d66f8ca1197cb1a1 zlib-1.2.11.tar.gz' | sha256sum -c
                 tar xvzf zlib-1.2.11.tar.gz
                 cd zlib-1.2.11
                 ./configure --static --prefix=/usr/x86_64-w64-mingw32 
                 make CC=x86_64-w64-mingw32-gcc AR=x86_64-w64-mingw32-ar CFLAGS="-DSTATICLIB -I/usr/x86_64-w64-mingw32/include" LDFLAGS="-L/usr/x86_64-w64-mingw32/lib" libz.a
                 make install CC=x86_64-w64-mingw32-gcc AR=x86_64-w64-mingw32-ar CFLAGS="-DSTATICLIB -I/usr/x86_64-w64-mingw32/include" LDFLAGS="-L/usr/x86_64-w64-mingw32/lib" 
      - run:
          name: Build LibPNG
          command: |         
                 cd src
                 wget http://download.sourceforge.net/libpng/libpng-1.6.16.tar.gz
                 echo '02f96b6bad5a381d36d7ba7a5d9be3b06f7fe6c274da00707509c23592a073ad  libpng-1.6.16.tar.gz' | sha256sum -c
                 tar xzvf libpng-1.6.16.tar.gz
                 cd libpng-1.6.16
                 CC=x86_64-w64-mingw32-gcc AR=x86_64-w64-mingw32-ar CFLAGS="-DSTATICLIB -I/usr/x86_64-w64-mingw32/include" LDFLAGS="-L/usr/x86_64-w64-mingw32/lib" ./configure --host=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32 --disable-shared
                 make && make install 
      - run:
          name: Build QREncode
          command: |         
                 cd src 
                 wget https://fukuchi.org/works/qrencode/qrencode-3.4.4.tar.gz
                 echo 'e794e26a96019013c0e3665cb06b18992668f352c5553d0a553f5d144f7f2a72 qrencode-3.4.4.tar.gz' | sha256sum -c
                 tar xzvf qrencode-3.4.4.tar.gz
                 cd qrencode-3.4.4
                 CC=x86_64-w64-mingw32-gcc \
                 AR=x86_64-w64-mingw32-ar \
                 CFLAGS="-DSTATICLIB -I/usr/x86_64-w64-mingw32/include" \
                 LDFLAGS="-L/usr/x86_64-w64-mingw32/lib" \
                 png_CFLAGS="-I/usr/x86_64-w64-mingw32/include" \
                 png_LIBS="-I/usr/x86_64-w64-mingw32/lib" \
                 ./configure --host=x86_64-w64-mingw32 --prefix=/usr/x86_64-w64-mingw32 --disable-shared --enable-static --without-tools
                 make -j4 install
      - run:
          name: Build MiniUPNPC
          command: |        
                 cd src 
                 wget http://miniupnp.free.fr/files/download.php?file=miniupnpc-1.9.tar.gz -O miniupnpc-1.9.tar.gz 
                 echo '2923e453e880bb949e3d4da9f83dd3cb6f08946d35de0b864d0339cf70934464 miniupnpc-1.9.tar.gz' | sha256sum -c
                 tar xzvf miniupnpc-1.9.tar.gz
                 cd miniupnpc-1.9
                 CC=x86_64-w64-mingw32-gcc \
                 AR=x86_64-w64-mingw32-ar \
                 CFLAGS="-DSTATICLIB -I/usr/x86_64-w64-mingw32/include" \
                 LDFLAGS="-L/usr/x86_64-w64-mingw32/lib" \
                 make libminiupnpc.a
                 mkdir /usr/x86_64-w64-mingw32/include/miniupnpc
                 cp *.h /usr/x86_64-w64-mingw32/include/miniupnpc
                 cp libminiupnpc.a /usr/x86_64-w64-mingw32/lib
      - run:
          name: Build BDB4.8
          command: |       
                 cd src 
                 wget 'http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz'
                 echo '12edc0df75bf9abd7f82f821795bcee50f42cb2e5f76a6a281b85732798364ef db-4.8.30.NC.tar.gz' | sha256sum -c
                 tar -xzvf db-4.8.30.NC.tar.gz
                 cd db-4.8.30.NC/build_unix/
                 CC=/usr/bin/x86_64-w64-mingw32-gcc CXX=/usr/bin/x86_64-w64-mingw32-g++ ../dist/configure --host=x86_64-w64-mingw32 --enable-cxx \
                 --enable-mingw --disable-replication --disable-shared --prefix=/usr/x86_64-w64-mingw32 
                 make -j4
                 make install
      - run:
          name: Build OpenSSL
          command: |      
                 cd src
                 wget 'http://www.openssl.org/source/openssl-1.0.2n.tar.gz'
                 echo '370babb75f278c39e0c50e8c4e7493bc0f18db6867478341a832a982fd15a8fe openssl-1.0.2n.tar.gz' | sha256sum -c
                 tar xvfz openssl-1.0.2n.tar.gz
                 cd openssl-1.0.2n
                 CFLAGS="-DSTATICLIB -I/usr/x86_64-w64-mingw32/include" \
                 LDFLAGS="-L/usr/x86_64-w64-mingw32/lib" \
                 ./Configure --cross-compile-prefix=x86_64-w64-mingw32- --prefix=/usr/x86_64-w64-mingw32 no-camellia no-capieng no-cast no-comp no-dso no-dtls1 \
                             no-ec_nistp_64_gcc_128 no-gost no-gmp no-heartbeats no-idea no-jpake no-krb5 no-libunbound no-md2 no-mdc2 no-rc4 no-rc5 no-rdrand \
                             no-rfc3779 no-rsax no-sctp no-sctp no-seed no-sha0 no-shared no-ssl-trace no-ssl2 no-ssl3 no-static_engine no-store no-unit-test \
                             no-weak-ssl-ciphers no-whirlpool no-zlib no-zlib-dynamic mingw64 && \
                 make depend
                 make -j4
                 make install
      - run:
          name: Build Qt
          command: |
                 wget 'http://download.qt-project.org/official_releases/qt/5.7/5.7.1/submodules/qtbase-opensource-src-5.7.1.7z'
                 wget 'http://download.qt-project.org/official_releases/qt/5.7/5.7.1/submodules/qttools-opensource-src-5.7.1.7z'
                 wget 'http://download.qt-project.org/official_releases/qt/5.7/5.7.1/submodules/qttranslations-opensource-src-5.7.1.7z'
                 echo 'a160e9c1403204f6a5c3a921de8530c3ff2e64f6608f259716f35f830e77f4d0  qtbase-opensource-src-5.7.1.7z' | sha256sum -c 
                 echo '904b1fb861c5b4923c0db1f1c1a06528a7c45c2170e13ca3eafbe10a54c366b4  qttools-opensource-src-5.7.1.7z' | sha256sum -c
                 echo '2b947f09b88333d5b2740835c1ceaab5abe2feeeb07a8e37f47d6b92d494f1e7  qttranslations-opensource-src-5.7.1.7z' | sha256sum -c
                 7z x qtbase-opensource-src-5.7.1.7z
                 7z x qttools-opensource-src-5.7.1.7z
                 7z x qttranslations-opensource-src-5.7.1.7z
                 cd qtbase-opensource-src-5.7.1/
                 ./configure -xplatform win32-g++ -device-option CROSS_COMPILE=x86_64-w64-mingw32- -nomake examples \
                             -release -c++std c++11 -confirm-license -dbus-runtime -no-alsa -prefix /usr/x86_64-w64-mingw32 \
                             -no-alsa -no-audio-backend -no-cups -no-egl -no-eglfs -no-feature-style-windowsmobile -no-feature-style-windowsce \
                             -no-freetype -no-gif -no-glib -no-gstreamer -no-icu -no-iconv -no-kms -no-linuxfb -no-libudev -no-mitshm -no-mtdev \
                             -no-pulseaudio -no-openvg -no-reduce-relocations -no-qml-debug -no-sql-db2 -no-sql-ibase -no-sql-oci -no-sql-tds \
                             -no-sql-mysql -no-sql-odbc -no-sql-psql -no-sql-sqlite -no-sql-sqlite2 -no-use-gold-linker -no-xinput2 -no-xrender \
                             -nomake tests -opensource -openssl-linked -optimized-qmake -pch -pkg-config -qt-libpng -qt-pcre \
                             -system-zlib -reduce-exports -static -silent -v -no-feature-printer -no-feature-printdialog -no-opengl -make libs 
                 echo "host_build: QT_CONFIG ~= s/system-zlib/zlib" >> mkspecs/qconfig.pri && \
                 echo "CONFIG += force_bootstrap" >> mkspecs/qconfig.pri && \
                 make sub-src-clean
                 cd ../qttranslations-opensource-src-5.7.1 && ../qtbase-opensource-src-5.7.1/bin/qmake qttranslations.pro -o Makefile && \
                 cd translations && ../../qtbase-opensource-src-5.7.1/bin/qmake translations.pro -o Makefile && cd ../.. &&\
                 cd qttools-opensource-src-5.7.1/src/linguist/lrelease/ && ../../../../qtbase-opensource-src-5.7.1/bin/qmake lrelease.pro -o Makefile
                 cd ../../../../qtbase-opensource-src-5.7.1/
                 make -C src sub-corelib sub-network sub-widgets sub-gui sub-plugins sub-testlib 
                 make -C ../qttools-opensource-src-5.7.1/src/linguist/lrelease 
                 make -C ../qttools-opensource-src-5.7.1/src/linguist/lrelease install_target
                 make -C ../qttranslations-opensource-src-5.7.1
                 make -C src sub-corelib-install_subtargets sub-network-install_subtargets sub-widgets-install_subtargets sub-gui-install_subtargets sub-plugins-install_subtargets sub-testlib-install_subtargets
                 make -C ../qttranslations-opensource-src-5.7.1 install_subtargets
                 cp bin/qmake /usr/x86_64-w64-mingw32/bin && cp -rf mkspecs /usr/x86_64-w64-mingw32/
      - run:
          name: Build Pink2d Daemon
          command: |                 
                 cd src 
                 make -f makefile.linux-mingw DEPSDIR=/usr/x86_64-w64-mingw32 TARGET_PLATFORM=x86_64
                 strip pink2d.exe
      - run:
         name: Build Pinkcoin-Qt
          command: |
                 /usr/x86_64-w64-mingw32/bin/qmake pinkcoin-qt.pro \
                 DEPS_INCLUDE_PATH=/usr/x86_64-w64-mingw32/include \
                 DEPS_LIB_PATH=/usr/x86_64-w64-mingw32/lib \
                 USE_UPNP=1 \
                 CONFIG+=c++11 \
                 USE_QRCODE=1 \
                 STATIC=all \
                 RELEASE=1 \
                 QRENCODE_INCLUDE_PATH=$DEPS_INCLUDE_PATH \
                 QRENCODE_LIB_PATH=$DEPS_LIB_PATH  \
                 BOOST_LIB_SUFFIX=-mt-s \
                 BOOST_THREAD_LIB_SUFFIX=_win32-mt-s \
                 BOOST_INCLUDE_PATH=$DEPS_INCLUDE_PATH/boost \
                 BOOST_LIB_PATH=$DEPS_LIB_PATH \
                 OPENSSL_INCLUDE_PATH=$DEPS_INCLUDE_PATH/openssl \
                 OPENSSL_LIB_PATH=$DEPS_LIB_PATH \
                 BDB_INCLUDE_PATH=$DEPS_INCLUDE_PATH \
                 BDB_LIB_PATH=$DEPS_LIB_PATH \
                 MINIUPNPC_INCLUDE_PATH=$DEPS_INCLUDE_PATH \
                 MINIUPNPC_LIB_PATH=$DEPS_LIB_PATH \
                 QMAKE_LRELEASE=/usr/x86_64-w64-mingw32/bin/lrelease
                 make -f Makefile.Release
      - run:
          name: Set Artifact name as env
          command: |
                  echo 'export BUILD_DATE=$(date "+%Y%m%d%H%M")' >> $BASH_ENV
                  echo 'export BUILD_NAME=Pinkcoin-CIbuild-$CIRCLE_BUILD_NUM-$BUILD_DATE' >> $BASH_ENV
      - run:
          name: Tar artifacts
          command: |
                  mkdir /tmp/build/
                  cp src/pink2d.exe /tmp/build
                  cp Pinkcoin-Qt.exe /tmp/build
                  tar cvfz /tmp/build/$BUILD_NAME.tar.gz .
      - store_artifacts:
          path: /tmp/build/
          destination: windows
